a_predict/urls.py
from django.urls import path, include

from .views import normal_views, admin_views

app_name = 'predict'

admin_patterns = [
    path('', admin_views.list_view, name='admin-list'),
    path('<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         admin_views.detail_view, name='admin-detail'),
    path('update/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         admin_views.update_view, name='admin-update'),
    path('export/statistics/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         admin_views.export_statistics, name='admin-export-statistics'),
    path('export/catalog/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         admin_views.export_catalog, name='admin-export-catalog'),
    path('export/answer/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         admin_views.export_answer, name='admin-export-answer'),
]

# admin_patterns = [
#     path('<str:category>/<int:year>/<str:ex>/<int:round>/print/', admin_views.print_view, name='print'),
#     path('export/predict/google_sheet',
#          admin_views.export_predict_data_to_google_sheet_view, name='export_predict_to_google'),
# ]

urlpatterns = [
    path('', normal_views.index_view, name='index'),
    path('<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         normal_views.detail_view, name='detail'),
    path('student/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/',
         normal_views.student_create_view, name='student-create'),
    path('answer/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/<str:subject_field>/',
         normal_views.answer_input_view, name='answer-input'),
    path('answer/confirm/<str:exam_type>/<int:exam_year>/<str:exam_exam>/<int:exam_round>/<str:subject_field>/',
         normal_views.answer_confirm_view, name='answer-confirm'),
    path('admin/', include(admin_patterns)),
]

log/urls.py
from django.urls import path

from .views import create_request_log

app_name = 'log'

urlpatterns = [
    path('request/', create_request_log, name='request_log'),
]

a_predict/models/police_models.py
from django.db import models

from .base_settings import Exam, Unit, Department, Student, AnswerCount, ChoiceMethod


class PoliceExam(Exam):
    # Override parent abstract model fields
    year = models.IntegerField(
        choices=ChoiceMethod.year_choices, default=ChoiceMethod.get_next_year(), verbose_name='연도')
    exam = models.CharField(
        max_length=2, choices=ChoiceMethod.police_exam_choices, default='경위', verbose_name='시험')

    class Meta:
        verbose_name = verbose_name_plural = "경위공채 성적예측 [1] 시험"
        db_table = 'a_predict_police_exam'


class PoliceUnit(Unit):
    # Override parent abstract model fields
    exam = models.CharField(
        max_length=2, choices=ChoiceMethod.police_exam_choices, default='경위', verbose_name='시험')
    name = models.CharField(
        max_length=20, choices=ChoiceMethod.police_unit_choices,
        default='경위', verbose_name='모집단위')

    class Meta:
        verbose_name = verbose_name_plural = "경위공채 성적예측 [2] 모집단위"
        db_table = 'a_predict_police_unit'


class PoliceDepartment(Department):
    # Override parent abstract model fields
    exam = models.CharField(
        max_length=2, choices=ChoiceMethod.police_exam_choices, default='경위', verbose_name='시험')
    unit = models.CharField(
        max_length=20, choices=ChoiceMethod.police_unit_choices,
        default='경위', verbose_name='모집단위')
    name = models.CharField(
        max_length=40, choices=ChoiceMethod.police_department_choices,
        default='일반', verbose_name='직렬')

    class Meta:
        verbose_name = verbose_name_plural = "경위공채 성적예측 [3] 직렬"
        db_table = 'a_predict_police_department'


class PoliceStudent(Student):
    # Override parent abstract model fields
    year = models.IntegerField(
        choices=ChoiceMethod.year_choices, default=ChoiceMethod.get_next_year(), verbose_name='연도')
    exam = models.CharField(
        max_length=2, choices=ChoiceMethod.police_exam_choices, default='경위', verbose_name='시험')
    unit = models.CharField(
        max_length=20, choices=ChoiceMethod.police_unit_choices,
        default='경위', verbose_name='모집단위')
    department = models.CharField(
        max_length=40, choices=ChoiceMethod.police_department_choices,
        default='일반', verbose_name='직렬')
    selection = models.CharField(
        max_length=20, choices=ChoiceMethod.police_subject_choices, default='minbeob', verbose_name='선택과목')

    class Meta:
        verbose_name = verbose_name_plural = "경위공채 성적예측 [4] 수험정보"
        db_table = 'a_predict_police_student'


class PoliceAnswerCount(AnswerCount):
    # Override parent abstract model fields
    year = models.IntegerField(
        choices=ChoiceMethod.year_choices, default=ChoiceMethod.get_next_year(), verbose_name='연도')
    exam = models.CharField(
        max_length=2, choices=ChoiceMethod.police_exam_choices, default='경위', verbose_name='시험')
    subject = models.CharField(
        max_length=20, choices=ChoiceMethod.police_subject_choices, default='hyeongsa', verbose_name='과목')
    count_5 = None

    class Meta:
        verbose_name = verbose_name_plural = "경위공채 성적예측 [5] 답안개수"
        db_table = 'a_predict_police_answer_count'

a_predict/views/admin_views.py
import io
import itertools
from urllib.parse import quote

import pandas as pd
from django.db.models import F, Value
from django.http import FileResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST

from a_predict.management import command_utils_new
from common.constants import icon_set_new
from common.decorators import only_staff_allowed
from common.utils import HtmxHttpRequest, update_context_data
from .base_info import PredictExamVars
from .. import models, utils, forms


@only_staff_allowed()
def list_view(request: HtmxHttpRequest):
    info = {'menu': 'predict', 'view_type': 'predict'}

    # Hx-Pagination header
    page = request.GET.get('page', 1)
    hx_pagination = request.headers.get('Hx-Pagination', 'main')
    is_all_student = hx_pagination == 'all_student'

    context = update_context_data(
        info=info, title='Predict', sub_title='합격 예측 [관리자 페이지]',
        icon_menu=icon_set_new.ICON_MENU['score'], pagination_url='?')

    # student
    qs_student = models.PsatStudent.objects.annotate(username=F('user__username')).order_by('id')
    student_page_data = utils.get_page_obj_and_range(qs_student, page)
    context = update_context_data(context, student_page_data=student_page_data)
    if is_all_student:
        return render(request, 'a_predict/snippets/admin_list_student.html#all_student', context)

    qs_psat_exam = models.PsatExam.objects.order_by('id').annotate(type=Value('psat'))
    qs_police_exam = models.PoliceExam.objects.order_by('id').annotate(type=Value('police'))
    qs_exam = list(qs_psat_exam) + list(qs_police_exam)
    exam_page_data = utils.get_page_obj_and_range(qs_exam)
    context = update_context_data(context, exam_list=qs_exam, exam_page_data=exam_page_data)
    return render(request, 'a_predict/predict_admin_list.html', context)


@only_staff_allowed()
def detail_view(request: HtmxHttpRequest, **kwargs):
    exam_vars = PredictExamVars(request, **kwargs)
    exam = exam_vars.get_exam()

    # page prefix
    header_stat = ['stat_all', 'stat_filtered']
    header_catalog = ['catalog_all', 'catalog_filtered']
    header_answer = [f'answer_{idx}' for idx in range(len(exam_vars.all_subject_fields))]

    # Hx-Pagination header
    page = request.GET.get('page', 1)
    hx_pagination = request.headers.get('Hx-Pagination', 'main')
    is_stat = hx_pagination in header_stat
    is_catalog = hx_pagination in header_catalog
    is_answer = hx_pagination in header_answer

    # template names
    template_stat = f'a_predict/snippets/admin_detail_statistics.html#{hx_pagination}'
    template_catalog = f'a_predict/snippets/admin_detail_catalog.html#{hx_pagination}'
    template_answer = f'a_predict/snippets/admin_detail_answer.html#{hx_pagination}'

    form = forms.UploadAnswerOfficialFileForm()

    context = update_context_data(
        # base info
        info=exam_vars.info, exam=exam,
        exam_vars=exam_vars, exam_type=exam_vars.exam_type,
        title='Predict', sub_title=exam_vars.sub_title,

        # icons
        icon_menu=icon_set_new.ICON_MENU['score'],
        icon_subject=icon_set_new.ICON_SUBJECT,
        icon_nav=icon_set_new.ICON_NAV,
        icon_search=icon_set_new.ICON_SEARCH,

        # default page settings
        pagination_url='?', header_stat=header_stat,
        header_catalog=header_catalog, header_answer=header_answer,
        answer_title=exam_vars.admin_sub_list, form=form,
    )
    qs_answer_count = exam_vars.get_qs_answer_count()
    qs_department = exam_vars.get_qs_department()
    qs_student = exam_vars.get_qs_student()

    # stat_page
    if is_stat:
        category = hx_pagination.split('_')[1]
        stat_page = get_stat_page(exam_vars, page)
        utils.update_stat_page(exam_vars, exam, stat_page[0], category)
        context = update_context_data(context, **{f'{hx_pagination}_page': stat_page})
        return render(request, template_stat, context)

    # catalog_page
    if is_catalog:
        category = hx_pagination.split('_')[1]
        catalog_page = get_catalog_page(exam_vars, exam, qs_student, category, page)
        utils.update_catalog_page(exam_vars, exam, qs_department, catalog_page[0], category)
        context = update_context_data(context, **{f'{hx_pagination}_page': catalog_page})
        return render(request, template_catalog, context)

    # answer_page
    if is_answer:
        answer_predict = exam_vars.get_data_answer_predict(qs_answer_count)
        answer_page = get_answer_page(qs_answer_count, exam_vars.all_subject_fields, page, hx_pagination)
        utils.update_answer_page(exam_vars, exam, answer_predict, answer_page[0])
        context = update_context_data(context, **{f'{hx_pagination}_page': answer_page})
        return render(request, template_answer, context)

    # main_page
    for header in header_stat:
        category = header.split('_')[1]
        stat_page = get_stat_page(exam_vars, page)
        utils.update_stat_page(exam_vars, exam, stat_page[0], category)
        context = update_context_data(context, **{f'{header}_page': stat_page})

    for header in header_catalog:
        category = header.split('_')[1]
        catalog_page = get_catalog_page(exam_vars, exam, qs_student, category, page)
        utils.update_catalog_page(exam_vars, exam, qs_department, catalog_page[0], category)
        context = update_context_data(context, **{f'{header}_page': catalog_page})

    answer_predict = exam_vars.get_data_answer_predict(qs_answer_count)
    for header in header_answer:
        answer_page = get_answer_page(qs_answer_count, exam_vars.all_subject_fields, page, header)
        utils.update_answer_page(exam_vars, exam, answer_predict, answer_page[0])
        context = update_context_data(context, **{f'{header}_page': answer_page})

    return render(request, 'a_predict/predict_admin_detail.html', context)


def get_stat_page(exam_vars: PredictExamVars, page):
    qs_department = exam_vars.get_qs_department()
    if exam_vars.is_psat:
        departments = [{'id': 'total', 'unit': '전체', 'department': '전체'}]
        departments.extend(qs_department)
    else:
        departments = [{'id': 'total', 'unit': '경위', 'get_name_display': '일반'}]
    stat_page: tuple = utils.get_page_obj_and_range(departments, page)
    return stat_page


def get_catalog_page(exam_vars, exam, qs_student, category, page):
    qs_student = utils.get_qs_student_for_admin_views(exam_vars, exam, qs_student, category)
    catalog_page: tuple = utils.get_page_obj_and_range(qs_student, page)
    return catalog_page


def get_answer_page(qs_answer_count, all_subject_fields, page, header):
    field_idx = int(header.split('_')[1])
    field = all_subject_fields[field_idx]
    qs_answer_count = qs_answer_count.filter(subject=field)
    answer_page: tuple = utils.get_page_obj_and_range(qs_answer_count, page)
    return answer_page


@only_staff_allowed()
def export_statistics(request: HtmxHttpRequest, **kwargs):
    exam_vars = PredictExamVars(request, **kwargs)
    exam = exam_vars.get_exam()
    qs_department = exam_vars.get_qs_department()

    unit = '전체' if exam_vars.is_psat else '경위'
    department = '전체' if exam_vars.is_psat else '일반'
    stat_all = [{'id': 'total', 'unit': unit, 'department': department}]
    stat_filtered = [{'id': 'total', 'unit': unit, 'department': department}]

    stat_all.extend(list(qs_department.values('id', 'unit', department=F('name'))))
    stat_filtered.extend(list(qs_department.values('id', 'unit', department=F('name'))))
    utils.update_stat_page(exam_vars, exam, stat_all, 'all')
    utils.update_stat_page(exam_vars, exam, stat_filtered, 'filtered')

    buffer = io.BytesIO()
    df_all = get_df_for_statistics(exam_vars, stat_all)
    df_filtered = get_df_for_statistics(exam_vars, stat_filtered)
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        df_all.to_excel(writer, sheet_name='all')
        df_filtered.to_excel(writer, sheet_name='filtered')
    buffer.seek(0)

    filename = f'{exam_vars.sub_title}_성적 통계.xlsx'
    filename = quote(filename)

    return FileResponse(buffer, as_attachment=True, filename=filename)


def get_df_for_statistics(exam_vars: PredictExamVars, data):
    level0 = ['ID', '모집단위', '직렬']
    for subject in exam_vars.admin_subject_list:
        level0 += [subject] * 5
    level1 = [''] * 3 + ['응시인원', '최고점수', '상위10%', '상위20%', '평균점수'] * 5
    col = [level0, level1]

    subject_num = len(exam_vars.admin_subject_list)
    data_edited = []
    for dt in data:
        append_list = [dt['id'], dt['unit'], dt['department']]
        for i in range(-1, subject_num - 1):
            val = dt['stat'][i]
            append_list.append(val['participants'] if val['participants'] else '')
            append_list.append(val['max'] if val['max'] else '')
            append_list.append(val['t10'] if val['t10'] else '')
            append_list.append(val['t20'] if val['t20'] else '')
            append_list.append(val['avg'] if val['avg'] else '')
        data_edited.append(append_list)
    df = pd.DataFrame(data=data_edited, columns=col)
    df.set_index(('ID', ''), inplace=True)
    return df


@only_staff_allowed()
def export_catalog(request: HtmxHttpRequest, **kwargs):
    exam_vars = PredictExamVars(request, **kwargs)
    exam = exam_vars.get_exam()
    qs_student = exam_vars.get_qs_student()
    qs_department = exam_vars.get_qs_department()

    catalog_all = utils.get_qs_student_for_admin_views(exam_vars, exam, qs_student, 'all')
    catalog_filtered = utils.get_qs_student_for_admin_views(exam_vars, exam, qs_student, 'filtered')
    utils.update_catalog_page(exam_vars, exam, qs_department, catalog_all, 'all')
    utils.update_catalog_page(exam_vars, exam, qs_department, catalog_filtered, 'filtered')

    buffer = io.BytesIO()
    df_all = get_df_for_catalog(exam_vars, catalog_all)
    df_filtered = get_df_for_catalog(exam_vars, catalog_filtered)
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:

common/views/base_views.py
from django.contrib.auth.decorators import login_not_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from ..utils import update_context_data


@login_not_required
def index_view(_):
    return redirect('psat:problem-list')


@login_not_required
def page_404(request):
    return render(request, '404.html', {})


@login_not_required
def ads(request):
    if request:
        return HttpResponse("google.com, pub-3543306443016219, DIRECT, f08c47fec0942fa0")


@login_not_required
def privacy(request):
    info = {'menu': 'privacy'}
    context = update_context_data(site_name='<PAEDISON>', info=info)
    return render(request, 'privacy.html', context)

a_predict/templates/a_predict/_base.html
{% extends 'list.html' %}
{% load static %}

{% block head_title %}{{ sub_title }}{% endblock %}
{% block page_image %}
<meta property="og:image" content="{% static 'image/predict/cover_psat_og.jpg' %}"/>
{% endblock page_image %}

{% block main %}
{% endblock main %}

a_predict/templates/a_predict/admin_list.html
{% extends 'a_predict/_base.html' %}
{% load static %}
{% load i18n %}
{% load psat_filter %}
{% load partials %}
{% load slippers %}
{% load humanize %}

{% block main %}
{{ info|json_script:'info' }}
<div class="pagetitle">
    <h1>{{ icon_menu|safe }} {{ title }}
        <span class="fs-6 text-secondary">{{ sub_title }}</span>
        <a class="btn btn-sm btn-outline-primary ms-2"
           hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-boost="true"
           href="{% url 'predict:index' %}">
            일반 페이지
        </a>
    </h1>
    <nav>
        <ol class="breadcrumb" hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-push-url="true">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" hx-post="{% url 'index' %}">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'predict:index' %}" hx-boost="true">Predict</a>
            </li>
            <li class="breadcrumb-item">
                <a class="active" href="{% url 'predict:admin-list' %}" hx-boost="true">Admin</a>
            </li>
        </ol>
    </nav>
</div><!-- Page Title End -->

<section class="section htmx-fade-in htmx-fade-out"
         hx-target="#main" hx-swap="innerHTML swap:0.25s">
    <div class="row">
        <div class="col-12">
            <div id="exam_list" class="card" hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-push-url="true">
                {% include 'a_predict/snippets/admin_list_exam.html' %}
            </div>
        </div>

        <div class="col-12">
            <div id="student_list" class="card htmx-fade-in htmx-fade-out"
                 hx-target="#student_list" hx-swap="innerHTML swap:0.25s">
                {% include 'a_predict/snippets/admin_list_student.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock main %}

a_predict/templates/a_predict/normal_detail.html
{% extends 'a_predict/_base.html' %}
{% load static %}
{% load i18n %}
{% load psat_filter %}

{% block page_image %}<meta property="og:image" content="{% static 'image/prime/2024/exam/message-1.jpg' %}"/>{% endblock %}
{% block main %}
{{ info|json_script:'info' }}
<div class="pagetitle">
    <h1>{{ icon_menu|safe }} {{ title }}
        <span class="fs-6 text-secondary">{{ sub_title }}</span>
        {% if user.is_staff %}
            <a class="btn btn-sm btn-outline-primary ms-2"
               hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-boost="true"
               href="{% url 'predict:admin-list' %}">
                관리자 페이지
            </a>
        {% endif %}
    </h1>
    <nav>
        <ol class="breadcrumb" hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-push-url="true">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}" hx-post="{% url 'index' %}">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'predict:index' %}" hx-boost="true">Predict</a>
            </li>
            <li class="breadcrumb-item active">
                <a class="active" href="" hx-boost="true">{{ exam.exam_abbr }}</a>
            </li>
        </ol>
    </nav>
</div><!-- Page Title End -->

<section class="section htmx-fade-in htmx-fade-out" hx-target="#main" hx-swap="innerHTML swap:0.25s">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body text-center p-4">
                    {% if exam.exam == '행시' %}
                        <img src="{% static 'image/banner/psat_2024_haengsi_main_cover.jpg' %}" class="mw-100" alt="Title"/>
                    {% elif exam.exam == '칠급' %}
                        <img src="{% static 'image/banner/psat_2024_chilgeup_main_cover.jpg' %}" class="mw-100" alt="Title"/>
                    {% elif exam.exam == '경위' %}
                        <img src="{% static 'image/banner/police_2025_main_cover.jpg' %}" class="mw-100" alt="Title"/>
                    {% endif %}
                    {% if not student %}
                        <div class="container d-sm-none my-4">
                            <p>수험생 여러분,<br/>그 동안 수고 많으셨습니다.</p>
                            <p>여러분의 합격을<br/>기원하는 마음과 함께<br/>
                                아래와 같이 합격예측시스템을<br/>제공해드리고 있습니다.</p>
                            <p>모집단위와 직렬 및 응시번호,<br/>이름을 입력하신 뒤,<br/>
                                과목별 시험 답안을 제출해주시면<br/>집계 후 여러분의<br/>
                                합격 여부를 예측해드립니다.</p>
                        </div>
                        <div class="container d-none d-sm-block my-4">
                            <p>수험생 여러분, 그 동안 수고 많으셨습니다.</p>
                            <p>여러분의 합격을 기원하는 마음과 함께</p>
                            <p>아래와 같이 합격예측시스템을 제공해드리고 있습니다.</p>
                            <p>모집단위와 직렬 및 응시번호, 이름을 입력하신 뒤,</p>
                            <p>과목별 시험 답안을 제출해주시면 집계 후</p>
                            <p>여러분의 합격 여부를 예측해드립니다.</p>
                        </div>
                        <div class="container p-0">
                            <div class="container">
                                <img src="{% static 'image/prime/2024/exam/message-1.jpg' %}" class="mw-100" alt="Message"/>
                                <img src="{% static 'image/prime/2024/exam/message-2.jpg' %}" class="mw-100" alt="Message"/>
                            </div>
                        </div>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <a class="btn btn-outline-danger mt-4"
                           hx-target="body" hx-swap="innerHTML swap:0.25s"
                           hx-get="{% url 'account_login' %}">
                            로그인이 필요합니다.
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if user.is_authenticated and student %}
            <div class="col-12" aria-label="수험 정보">
                <div id="info_student" class="card htmx-fade-in htmx-fade-out">
                    {% include 'a_predict/snippets/index_info_student.html' %}
                </div>
            </div>
{#            student_id: {{ student.id }}<br/>#}
{#            exam_id: {{ exam.id }}<br/>#}
{#            현재 시각: {{ current_time }}<br/>#}
{#            페이지 오픈 시각: {{ exam.page_opened_at }}<br/>#}
{#            시험 시작 시각: {{ exam.started_at }}<br/>#}
{#            시험 종료 시각: {{ exam.finished_at }}<br/>#}
{#            예상 정답 공개 시각: {{ exam.answer_predict_opened_at }}<br/>#}
{#            정답 공개 시각: {{ exam.answer_official_opened_at }}<br/>#}

            <div class="col-12" aria-label="답안 제출 현황">
                <div id="info_answer" class="card htmx-fade-in htmx-fade-out">
                    {% include 'a_predict/snippets/index_info_answer.html' %}
                </div>
            </div>

            {% if exam.is_answer_official_opened %}
                <div class="col-12" aria-label="성적 예측 I [전체 데이터]">
                    <div id="sheet_score" class="card htmx-fade-in htmx-fade-out">
                        {% include 'a_predict/snippets/index_sheet_score_all.html' %}
                    </div>
                </div>
                {% if student.answer_all_confirmed_at < exam.answer_official_opened_at %}
                    <div class="col-12" aria-label="성적 예측 II [정답 공개 전 데이터]">
                        <div id="sheet_score" class="card htmx-fade-in htmx-fade-out">
                            {% include 'a_predict/snippets/index_sheet_score_filtered.html' %}
                        </div>
                    </div>
                {% endif %}
            {% endif %}

            {% if exam.is_collecting_answer or exam.is_answer_predict_opened %}
                <div class="col-12" aria-label="예상 정답">
                    <div id="info_student" class="card htmx-fade-in htmx-fade-out">
                        {% include 'a_predict/snippets/index_sheet_answer_predict.html' %}
                    </div>
                </div>
            {% endif %}
{#                <div class="col-12" aria-label="예상 정답">#}
{#                    <div id="info_student" class="card htmx-fade-in htmx-fade-out">#}
{#                        {% include 'a_predict/snippets/index_sheet_answer_predict.html' %}#}
{#                    </div>#}
{#                </div>#}

            <div class="col-12" aria-label="정답 확인">
                <div id="sheet_answer" class="card htmx-fade-in htmx-fade-out">
                    {% include 'a_predict/snippets/index_sheet_answer_submit.html' %}
                </div>
            </div>
        {% endif %}
        <div class="col-12">
            <div class="card">
                <div class="card-body p-4">
                    <div class="iframe_container">
                        <iframe class="iframe_content" title="YouTube video player"
                                src="https://www.youtube.com/embed/Fal8-8NRabY?si=4765xVgFBlV_l_Kh"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock main %}

a_predict/templates/a_predict/student_create.html
{% extends 'a_predict/_base.html' %}
{% load static %}
{% load i18n %}

{% block main %}
{{ info|json_script:'info' }}
<div class="pagetitle" hx-target="#main" hx-swap="innerHTML swap:0.25s" hx-boost="true">
    <h1>{{ icon_menu|safe }} {{ title }}
        <span class="fs-6 text-secondary">{{ sub_title }}</span>
        {% if user.is_staff %}
            <a class="btn btn-sm btn-outline-primary ms-2" href="{% url 'predict:admin-list' %}">
                관리자 페이지
            </a>
        {% endif %}
    </h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a class="active" href="{% url 'predict:index' %}">Predict</a>
            </li>
            <li class="breadcrumb-item">{{ exam.get_year_display }}</li>
        </ol>
    </nav>
</div><!-- Page Title End -->

<section class="section htmx-fade-in htmx-fade-out" hx-target="#main" hx-swap="innerHTML swap:0.25s">
    <div class="row">
        <div class="col-12">
            <div class="card">
                    <a href="{{ exam_vars.url_detail }}" hx-boost="true">
                        {% if exam.exam == '칠급' %}
                            <img src="{% static 'image/banner/psat_2024_chilgeup_predict_banner.jpg' %}" class="mw-100" alt="Title"/>
                        {% elif exam.exam == '경위' %}
                            <img src="{% static 'image/banner/police_2025_predict_banner.jpg' %}" class="mw-100" alt="Title"/>
                        {% endif %}
                    </a>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                <div class="card-header m-0">
                    <span class="text-primary">
                        {{ exam.get_exam_display }}{% if exam.exam == '경위' %}(일반 직렬){% endif %} 수험정보
                    </span>
                </div>
                <div class="card-body p-4">
                    <div id="infoStudent" class="htmx-fade-in htmx-fade-out">
                        {% include 'a_predict/snippets/create_info_student.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock main %}