log/urls.py
from django.urls import path

from .views import create_request_log

app_name = 'log'

urlpatterns = [
    path('request/', create_request_log, name='request_log'),
]

score/urls.py
from django.urls import path, include

from score.views.psat_v4 import score_views, student_views
from score.views.prime_v3 import normal_views, admin_views
from score.views.predict_v1 import (
    normal_views as predict_normal_views,
    test_views as predict_test_views,
    admin_views as predict_admin_views,
)

app_name = 'score_old'

psat_urlpatterns = [
    path('', score_views.list_view, name='psat-list'),

    path('detail/', score_views.detail_view, name='psat-detail'),
    path('detail/<int:year>/<str:ex>/', score_views.detail_view, name='psat-detail-year-ex'),
    path('detail/filter/exam/', score_views.exam_filter, name='psat-filter'),

    path('submit/<int:problem_id>/', score_views.submit_view, name='psat-submit'),
    path('confirm/modal/', score_views.confirm_modal_view, name='psat-confirm-modal'),

    path('no_student/modal/<int:year>/<str:ex>/',
         student_views.no_student_modal_view, name='psat-no-student-modal'),

    path('student/create/modal/<int:year>/<str:ex>/',
         student_views.student_create_modal_view, name='psat-student-create-modal'),
    path('student/create/department/',
         student_views.student_create_department, name='psat-student-create-department'),
    path('student/create/',
         student_views.student_create_view, name='psat-student-create'),

    path('student/update/modal/<int:student_id>/',
         student_views.student_update_modal_view, name='psat-student-update-modal'),
    path('student/update/department/<int:student_id>/',
         student_views.student_update_department, name='psat-student-update-department'),
    path('student/update/<int:student_id>/',
         student_views.student_update_view, name='psat-student-update'),
]

prime_urlpatterns = [
    path('', normal_views.list_view, name='prime-list'),

    path('<int:year>/<int:round>/', normal_views.detail_view, name='prime-detail'),
    path('<int:year>/<int:round>/print/', normal_views.detail_print_view, name='prime-print'),

    path('<int:year>/<int:round>/no_open/', normal_views.no_open_modal_view, name='prime-no-open-modal'),
    path('<int:year>/<int:round>/no_student/', normal_views.no_student_modal_view, name='prime-no-student-modal'),

    path('predict/no_open/', normal_views.no_predict_open_modal, name='prime-no-predict-open-modal'),

    path('<int:year>/<int:round>/student/modal/',
         normal_views.student_connect_modal_view, name='prime-student-connect-modal'),
    path('<int:year>/<int:round>/student/connect/',
         normal_views.student_connect_view, name='prime-student-connect'),
    path('<int:year>/<int:round>/student/reset/',
         normal_views.student_reset_view, name='prime-student-reset'),
]

prime_admin_urlpatterns = [
    path('', admin_views.list_view, name='prime-admin-list'),
    path('student/', admin_views.list_student_view, name='prime-admin-list-student'),

    path('<int:year>/<int:round>/', admin_views.detail_view, name='prime-admin-detail'),
    path('search/<int:year>/<int:round>/', admin_views.catalog_view, name='prime-admin-catalog-year-round'),

    path('print/<int:year>/<int:round>/', admin_views.print_view, name='prime-admin-print'),
    path('print/<int:year>/<int:round>/<int:student_id>',
         admin_views.individual_student_print_view, name='prime-admin-individual-student-print'),

    path('export/transcript/<int:year>/<int:round>/',
         admin_views.export_transcript_to_pdf_view, name='prime-admin-export-transcript'),
    path('export/statistics/<int:year>/<int:round>/',
         admin_views.export_statistics_to_excel_view, name='prime-admin-export-statistics'),
    path('export/analysis/<int:year>/<int:round>/',
         admin_views.export_analysis_to_excel_view, name='prime-admin-export-analysis'),
    path('export/students_score/<int:year>/<int:round>/',
         admin_views.export_scores_to_excel_view, name='prime-admin-export-scores'),
]

predict_urlpatterns = [
    path('', predict_normal_views.index_view, name='predict-index'),
    path('test/', predict_test_views.TestView.as_view(), name='predict-test'),

    path('student/', predict_normal_views.student_create_view, name='predict-student-create'),
    path('student/department/',
         predict_normal_views.student_create_department, name='predict-student-create-department'),

    path('answer/<str:sub>/', predict_normal_views.answer_input_view, name='predict-answer-input'),
    path('answer/<str:sub>/submit/', predict_normal_views.answer_submit_view, name='predict-answer-submit'),
    path('answer/<str:sub>/confirm/', predict_normal_views.answer_confirm_view, name='predict-answer-confirm'),

    path('update/info_answer/', predict_normal_views.update_info_answer, name='predict-update-info-answer'),
    path('update/sheet_answer/', predict_normal_views.update_sheet_answer, name='predict-update-sheet-answer'),
    path('update/sheet_score/', predict_normal_views.update_sheet_score, name='predict-update-sheet-score'),
]

predict_admin_urlpatterns = [
    path('', predict_admin_views.list_view, name='predict-admin-list'),
    path('student/', predict_admin_views.list_student_view, name='predict-admin-list-student'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/', predict_admin_views.detail_view, name='predict-admin-detail'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/catalog/', predict_admin_views.catalog_view, name='predict-admin-catalog'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/user<int:user_id>/',
         predict_admin_views.individual_index_view, name='predict-admin-individual'),

    path('test/', predict_admin_views.test_view, name='predict-admin-test'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/answer/',
         predict_admin_views.update_answer, name='predict-admin-update-answer'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/score/',
         predict_admin_views.update_score, name='predict-admin-update-score'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/statistics/',
         predict_admin_views.update_statistics, name='predict-admin-update-statistics'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/print/', predict_admin_views.print_view, name='predict-admin-print'),
    # path('print/<int:year>/<int:round>/<int:student_id>',
    #      predict_admin_views.individual_student_print_view, name='predict-admin-individual-student-print'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/transcript',
         predict_admin_views.export_transcript_to_pdf_view, name='predict-admin-export-transcript'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/statistics/',
         predict_admin_views.export_statistics_to_excel_view, name='predict-admin-export-statistics'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/analysis/',
         predict_admin_views.export_analysis_to_excel_view, name='predict-admin-export-analysis'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/students_score/',
         predict_admin_views.export_scores_to_excel_view, name='predict-admin-export-scores'),
    path('export/predict/google_sheet',
         predict_admin_views.export_predict_data_to_google_sheet_view, name='predict-admin-export-predict-to-google'),
]

urlpatterns = [
    path('psat/', include(psat_urlpatterns)),  # Psat score current version
    path('prime/', include(prime_urlpatterns)),  # Prime score current version
    path('prime/admin/', include(prime_admin_urlpatterns)),  # Prime_admin score current version
    path('predict/', include(predict_urlpatterns)),  # Predict score current version
    path('predict/admin/', include(predict_admin_urlpatterns)),  # Predict_admin score current version
]
#
# urlpatterns = [
#     path('psat/', include('score.urls_module.psat_v4')),  # Psat score current version
#     # path('psat/', include('score.urls_module.psat_v3')),  # Psat score current version
#     # path('psat_v2/', include('score.urls_module.psat_v2')),  # Psat score version 2.0
#     # path('psat_v1/', include('score.urls_module.psat_v1')),  # Psat score version 1.0
#
#     path('prime/', include('score.urls_module.prime_v3')),  # Prime score current version
#     # path('prime/', include('score.urls_module.prime_v2')),  # Prime score version 2.0
#     # path('prime_v1/', include('score.urls_module.prime_v1')),  # Prime score version 1.0
#
#     path('prime/admin/', include('score.urls_module.prime_admin_v3')),  # Prime_admin score current version
#     # path('prime/admin/', include('score.urls_module.prime_admin_v2')),  # Prime_admin score version 2.0
#     # path('prime_v1/admin/', include('score.urls_module.prime_admin_v1')),  # Prime_admin score version 1.0
#
#     path('predict/', include('score.urls_module.predict_v1')),  # Predict score current version
#     path('predict/admin/', include('score.urls_module.predict_admin_v1')),  # Predict_admin score current version
# ]

a_leet/forms.py
from datetime import time

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from common.utils import get_local_time
from . import models


class LeetForm(forms.ModelForm):
    class Meta:
        model = models.Leet
        fields = ['year', 'is_active']
        widgets = {
            'year': forms.Select(attrs={'class': 'form-select'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class LeetActiveForm(forms.ModelForm):
    class Meta:
        model = models.Leet
        fields = ['is_active']
        widgets = {
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class ProblemUpdateForm(forms.Form):
    year = forms.ChoiceField(
        label='연도',
        choices=models.choices.year_choice,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    exam = forms.ChoiceField(
        label='시험',
        choices=models.choices.exam_choice,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    file = forms.FileField(
        label='문제 업데이트',
        widget=forms.FileInput(attrs={'class': 'form-control'})
    )


class ProblemTagForm(forms.ModelForm):
    class Meta:
        model = models.ProblemTag
        fields = []


class ProblemCommentForm(forms.ModelForm):
    class Meta:
        model = models.ProblemComment
        fields = ['content', 'parent']


class ProblemMemoForm(forms.ModelForm):
    class Meta:
        model = models.ProblemMemo
        fields = ['content']


class ProblemCollectionForm(forms.ModelForm):
    title = forms.CharField(
        label='', label_suffix='',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': _('Input new collection name')}
        )
    )

    class Meta:
        model = models.ProblemCollection
        fields = ['title']


class PredictStudentForm(forms.Form):
    serial = forms.CharField(
        max_length=10, label='수험번호',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '수험번호'}),
    )
    name = forms.CharField(
        max_length=20, label='이름',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '이름'}),
    )
    password = forms.CharField(
        max_length=10, label='비밀번호',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '비밀번호'}),
    )
    # prime_id = forms.CharField(
    #     max_length=15, label='프라임법학원 ID', required=False,
    #     widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '프라임법학원 ID'}),
    # )
    aspiration_1 = forms.ChoiceField(
        label='1지망', required=False,
        choices=[('', '1지망')] + models.choices.university_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    aspiration_2 = forms.ChoiceField(
        label='2지망', required=False,
        choices=[('', '2지망')] + models.choices.university_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    school = forms.ChoiceField(
        label='출신대학', required=False,
        choices=[('', '출신대학 [선택]')] + models.choices.university_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    major = forms.ChoiceField(
        label='출신대학', required=False,
        choices=[('', '전공 [선택]')] + models.choices.major_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    gpa = forms.FloatField(
        label='학점(GPA)', required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '학점(GPA) [선택]'}),
        error_messages={'invalid': '실수 형태의 숫자를 입력해주세요.'}
    )
    gpa_type = forms.ChoiceField(
        label='학점(GPA) 종류', required=False,
        choices=[('', '학점(GPA) 종류')] + models.choices.gpa_type_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    english = forms.CharField(
        max_length=10, label='공인 영어성적 [선택]', required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '공인 영어성적 [선택]'}),
    )
    english_type = forms.ChoiceField(
        label='공인 영어성적 종류', required=False,
        choices=[('', '공인 영어성적 종류')] + models.choices.english_type_choice(),
        widget=forms.Select(attrs={'class': 'form-select'}),
    )


class UploadFileForm(forms.Form):
    file = forms.FileField(label='업로드 파일', widget=forms.FileInput(attrs={'class': 'form-control'}))


class PredictLeetForm(forms.Form):
    year = forms.ChoiceField(
        label='연도', initial=timezone.now().year+1, choices=models.choices.year_choice,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    page_open_date = forms.DateField(
        label='페이지 오픈일', initial=timezone.now(),
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
    )
    exam_date = forms.DateField(
        label='시험일', initial=timezone.now(),
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
    )
    predict_close_date = forms.DateField(
        label='합격 예측 종료일', initial=timezone.now(),
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
    )
    exam_start_time = forms.TimeField(
        label='시험 시작 시각', initial=time(9, 0),
        widget=forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
    )
    exam_finish_time = forms.TimeField(
        label='시험 종료 시각', initial=time(15, 50),
        widget=forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
    )
    answer_predict_open_time = forms.TimeField(
        label='예상 정답 공개 시각', initial=time(18, 30),
        widget=forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
    )
    answer_official_open_time = forms.TimeField(
        label='공식 정답 공개 시각', initial=time(21, 00),
        widget=forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
    )

    def clean(self):
        cleaned_data = super().clean()

        try:
            page_open_date = cleaned_data['page_open_date']
            exam_date = cleaned_data['exam_date']
            predict_close_date = cleaned_data['predict_close_date']
            exam_start_time = cleaned_data['exam_start_time']
            exam_finish_time = cleaned_data['exam_finish_time']
            answer_predict_open_time = cleaned_data['answer_predict_open_time']
            answer_official_open_time = cleaned_data['answer_official_open_time']
        except KeyError as e:
            raise ValidationError(f"Missing field: {e.args[0]}")

        if page_open_date:
            cleaned_data['page_opened_at'] = get_local_time(page_open_date)
        if exam_date:
            cleaned_data['exam_started_at'] = get_local_time(exam_date, exam_start_time)
        cleaned_data['exam_finished_at'] = get_local_time(exam_date, exam_finish_time)
        cleaned_data['answer_predict_opened_at'] = get_local_time(exam_date, answer_predict_open_time)
        cleaned_data['answer_official_opened_at'] = get_local_time(exam_date, answer_official_open_time)
        if predict_close_date:
            cleaned_data['predict_closed_at'] = get_local_time(predict_close_date)

        return cleaned_data

templates/score/psat_v4/snippets/score_modal.html
{% load slippers %}
{% load partials %}

{% partialdef no_student_modal %} {# no_student_modal partial #}
    {% #modal header='수험 정보 오류' %}
        <h5 class="modal-title mx-auto fw-bold">
            <span class="text-danger" hx-trigger="load delay:1s"
                  hx-target="#modalContainer" hx-push-url="false"
                  hx-swap="innerHTML swap:0.25s"
                  hx-post="{% url 'score_old:psat-student-create-modal' year ex %}">
                수험정보를 입력해주세요.
            </span>
        </h5>
    {% /modal %}
{% endpartialdef no_student_modal %}

{% partialdef student_create %} {# student_create partial #}
    {% #modal header=header size=" " %}
        <form>
            <input id="id_year" type="text" name="year" value="{{ year }}" aria-label="Year" hidden>
            <input name="ex" value="{{ ex }}" aria-label="Exam" hidden>
            <div class="form-floating">
                <input id="id_serial" class="form-control form-control-sm"
                       type="text" placeholder="수험번호(선택사항)" name="serial"/>
                <label for="id_serial">수험번호(선택사항)</label>
            </div>
            <select id="id_unit" class="form-select mt-3" name="unit_id" aria-label="Select unit"
                    hx-post="{% url 'score_old:psat-student-create-department' %}"
                    hx-trigger="change" hx-target="#student_create_department">
                <option selected>모집 단위를 선택해주세요.</option>
                {% for unit in units %}
                    <option value="{{ unit.id }}">{{ unit.name }}</option>
                {% endfor %}
            </select>
            <div id="student_create_department" class="input-group mt-3">
            </div>
        </form>
    {% /modal %}
{% endpartialdef student_create %}

{% partialdef student_create_department %} {# student_create_department partial #}
    <select id="id_department" class="form-select" name="department" aria-label="Select department">
        <option selected>직렬을 선택해주세요.</option>
        {% for department in departments %}
            <option value="{{ department.id }}">
                {{ department.name }}
            </option>
        {% endfor %}
    </select>
    <button class="btn btn-outline-secondary" type="submit" data-bs-dismiss="modal"
            hx-swap="innerHTML swap:0.25s"
            hx-post="{% url 'score_old:psat-student-create' %}" hx-target="#main">
        입력
    </button>
{% endpartialdef student_create_department %}

{% partialdef student_update %} {# student_update partial #}
    {% #modal header=header size=" " %}
        <form>
            <input id="id_year" type="text" name="year" value="{{ student.year }}" aria-label="Year" hidden>
            <div class="form-floating">
                <input id="id_serial" class="form-control form-control-sm"
                       type="text" placeholder="수험번호" name="serial"
                       value="{{ student.serial|default:'' }}"/>
                <label for="id_serial">수험번호(선택사항)</label>
            </div>
            <select id="id_unit" class="form-select mt-3" name="unit_id" aria-label="Select unit"
                    hx-post="{% url 'score_old:psat-student-update_department' student.id %}"
                    hx-trigger="change" hx-target="#student_update_department">
                <option selected>모집 단위를 선택해주세요.</option>
                {% for unit in units %}
                    <option value="{{ unit.id }}"
                            {% if unit == student.department.unit %}selected{% endif %}>
                        {{ unit.name }}
                    </option>
                {% endfor %}
            </select>
            <div id="student_update_department" class="input-group mt-3">
                {% partial student_update_department %}
            </div>
        </form>
    {% /modal %}
{% endpartialdef student_update %}

{% partialdef student_update_department %} {# student_update_department partial #}
    <select id="id_department" class="form-select" name="department" aria-label="Select department">
        <option selected>직렬을 선택해주세요.</option>
        {% for department in departments %}
            <option value="{{ department.id }}"
                    {% if department == student.department %}selected{% endif %}>
                {{ department.name }}
            </option>
        {% endfor %}
    </select>
    <button class="btn btn-outline-secondary" type="submit" data-bs-dismiss="modal" hx-swap="innerHTML swap:0.25s"
            hx-post="{% url 'score_old:psat-student-update' student.id %}" hx-target="#main">
        수정
    </button>
{% endpartialdef student_update_department %}

{% partialdef score_confirmed %} {# score_confirmed partial #}
    {% #modal header='최종 답안 제출' %}
        <h5 class="modal-title mx-auto fw-bold">
            {% if is_complete %}
                <span class="text-success" hx-trigger="load delay:0.25s"
                      hx-target="#main" hx-push-url="false"
                      hx-get="{% url 'score_old:psat-detail-year-ex' psat.year psat.exam.abbr %}">
                    답안이 정상적으로<br/>제출되었습니다.
                </span>
                <script>
                    function closeModal(el) {
                        if (el) {
                            setTimeout(function () {
                                    el.click();
                                }, 1000);
                        }
                    }

                    if (typeof button === 'undefined') {
                        let button = document.querySelector('.btn-close');
                        closeModal(button);
                    } else {
                        closeModal(button);
                    }
                </script>
            {% else %}
                <span class="text-danger">모든 문제의 답안을<br/>제출해주세요.</span>
            {% endif %}
        </h5>
    {% /modal %}
{% endpartialdef score_confirmed %}

templates/score/psat_v4/snippets/score_student.html
{% load psat_filter %}
{% load partials %}
{% load slippers %}

<nav>
    <div class="nav nav-tabs nav-tabs-colored" id="studentInfoTab" role="tablist">
        {% #nav_tab prefix='my' id='0' %}수험 정보{% /nav_tab %}
    </div>
</nav>

<div class="tab-content" id="studentInfoContent">
    {% #nav_content prefix='info' id='0' %}
        {% #responsive_table %}
            {% if student %}
                <tbody>
                    <tr class="d-table-row d-md-none">
                        <td class="col-3 text-nowrap">수험번호</td>
                        <td>
                            {{ student.serial }}

                            {% partialdef update_student inline=True %} {# update_student partial #}
                                <a class="badge rounded-pill text-bg-warning mx-2"
                                   hx-get="{% url 'score_old:psat-student-update-modal' student.id %}" href=""
                                   hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
                                   data-bs-toggle="modal" data-bs-target="#modalContainer">
                                    수정
                                </a>
                            {% endpartialdef update_student %}

                        </td>
                    </tr>
                    <tr class="d-table-row d-md-none">
                        <td>모집단위</td>
                        <td>{{ student.unit_name }} {% partial update_student %}</td>
                    </tr>
                    <tr class="d-table-row d-md-none">
                        <td>직렬</td>
                        <td>{{ student.department_name }} {% partial update_student %}</td>
                    </tr>
                    <tr class="d-none d-md-table-row">
                        <td>
                            수험번호
                            {% if student.serial %}
                                : {{ student.serial }}
                            {% endif %}
                            {% partial update_student %}
                        </td>
                        <td>모집단위 : {{ student.unit_name }} {% partial update_student %}</td>
                        <td>직렬 : {{ student.department_name }} {% partial update_student %}</td>
                    </tr>
                </tbody>
            {% else %}
                <tbody>
                    <tr class="text-center align-middle">
                        <td class="text-danger fs-6 py-4">
                            <a class="badge rounded-pill text-bg-danger"
                               hx-get="{% url 'score_old:psat-student-create-modal' year ex %}" href=""
                               hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
                               data-bs-toggle="modal" data-bs-target="#modalContainer">
                                수험 정보를 입력해주세요.
                            </a>
                        </td>
                    </tr>
                </tbody>
            {% endif %}
        {% /responsive_table %}
    {% /nav_content %}
</div>