a_psat/urls.py
from django.urls import path, include

from .views import admin_views, normal_views

app_name = 'psat'

admin_official_patterns = [
    path('list/', admin_views.official_list_view, name='admin-official-list'),
    path('detail/<int:pk>/', admin_views.official_detail_view, name='admin-official-detail'),

    path('create/', admin_views.official_psat_create_view, name='admin-official-psat-create'),
    path('active/<int:pk>/', admin_views.official_psat_active_view, name='admin-official-psat-active'),
    path('update/', admin_views.official_update_view, name='admin-official-update'),
    path('update/<int:pk>/', admin_views.official_update_by_psat_view, name='admin-official-update-by-psat'),
]

admin_predict_patterns = [
    path('list/', admin_views.predict_list_view, name='admin-predict-list'),
    path('detail/<int:pk>/', admin_views.predict_detail_view, name='admin-predict-detail'),

    path('create/', admin_views.predict_create_view, name='admin-predict-create'),
    path('update/<int:pk>/', admin_views.predict_update_view, name='admin-predict-update'),
    path('student/<int:pk>/', admin_views.predict_student_detail_view, name='admin-predict-student-detail'),

    path('print/statistics/<int:pk>/', admin_views.predict_statistics_print, name='admin-predict-statistics-print'),
    path('print/catalog/<int:pk>/', admin_views.predict_catalog_print, name='admin-predict-catalog-print'),
    path('print/answer/<int:pk>/', admin_views.predict_answer_print, name='admin-predict-answer-print'),

    path('excel/statistics/<int:pk>/', admin_views.predict_statistics_excel, name='admin-predict-statistics-excel'),
    path('excel/prime_id/<int:pk>/', admin_views.predict_prime_id_excel, name='admin-predict-prime_id-excel'),
    path('excel/catalog/<int:pk>/', admin_views.predict_catalog_excel, name='admin-predict-catalog-excel'),
    path('excel/answer/<int:pk>/', admin_views.predict_answer_excel, name='admin-predict-answer-excel'),
]

admin_study_patterns = [
    path('list/', admin_views.study_list_view, name='admin-study-list'),
    path('detail/<str:study_type>/<int:pk>/', admin_views.study_detail_view, name='admin-study-detail'),

    path('create/category/', admin_views.study_create_category_view, name='admin-study-category-create'),
    path('create/curriculum/', admin_views.study_create_curriculum_view, name='admin-study-curriculum-create'),
    path('create/organization/', admin_views.study_create_organization_view, name='admin-study-organization-create'),
    path('create/student/', admin_views.study_create_student_view, name='admin-study-student-create'),

    path('upload/category/', admin_views.study_upload_category_view, name='admin-study-category-upload'),
    path('upload/curriculum/', admin_views.study_upload_curriculum_view, name='admin-study-curriculum-upload'),
    path('upload/answer/', admin_views.study_upload_answer_view, name='admin-study-answer-upload'),

    path('update/category/<int:pk>/', admin_views.study_update_category_view, name='admin-study-category-update'),
    path('update/curriculum/<int:pk>/', admin_views.study_update_curriculum_view, name='admin-study-curriculum-update'),

    path('student/<int:pk>/', admin_views.study_student_detail_view, name='admin-study-student-detail'),

    path('excel/statistics/<str:study_type>/<int:pk>/',
         admin_views.study_statistics_excel, name='admin-study-statistics-excel'),
    path('excel/catalog/<str:study_type>/<int:pk>/',
         admin_views.study_catalog_excel, name='admin-study-catalog-excel'),
    path('excel/answer/<str:study_type>/<int:pk>/',
         admin_views.study_answer_excel, name='admin-study-answer-excel'),
]

admin_tag_patterns = [
    path('list/', admin_views.tag_list_view, name='admin-tag-list'),
    path('detail/<int:slug>/', admin_views.tag_detail_view, name='admin-tag-detail'),

    path('import/problem/list/', admin_views.tag_import_problem_list, name='admin-tag-import-problem-list'),
    path('export/problem/list/', admin_views.tag_export_problem_list, name='admin-tag-export-problem-list'),

    path('import/tag/list/', admin_views.tag_import_tag_list, name='admin-tag-import-tag-list'),
    path('export/tag/list/', admin_views.tag_export_tag_list, name='admin-tag-export-tag-list'),
]

admin_patterns = [
    path('official/', include(admin_official_patterns)),
    path('predict/', include(admin_predict_patterns)),
    path('study/', include(admin_study_patterns)),
    path('tag/', include(admin_tag_patterns)),
]

collection_patterns = [
    path('list/', normal_views.official_collection_list_view, name='collection-list'),
    path('create/', normal_views.official_collection_create, name='collection-create'),
    path('detail/<int:pk>/', normal_views.official_collection_detail_view, name='collection-detail'),
]

official_patterns = [
    path('list/', normal_views.official_problem_list_view, name='problem-list'),
    path('detail/<int:pk>/', normal_views.official_problem_detail_view, name='problem-detail'),

    path('like/<int:pk>/', normal_views.official_like_problem, name='like-problem'),
    path('rate/<int:pk>/', normal_views.official_rate_problem, name='rate-problem'),
    path('solve/<int:pk>/', normal_views.official_solve_problem, name='solve-problem'),
    path('memo/<int:pk>/', normal_views.official_memo_problem, name='memo-problem'),
    path('tag/<int:pk>/', normal_views.official_tag_problem, name='tag-problem'),
    path('collection/', include(collection_patterns)),
    path('collect/<int:pk>/', normal_views.official_collect_problem, name='collect-problem'),
    path('annotate/<int:pk>/', normal_views.official_annotate_problem, name='annotate-problem'),

    # path('comment/<int:pk>/', problem_views.comment_problem, name='comment-problem'),
    #
    # path('comment/create/<int:pk>/', problem_views.comment_problem_create, name='comment-problem-create'),
    # path('comment/update/<int:pk>/', problem_views.comment_problem_update, name='comment-problem-update'),
    # path('comment/delete/<int:pk>/', problem_views.comment_problem_delete, name='comment-problem-delete'),
]

# comment_patterns = [
#     path('', problem_views.comment_list_view, name='comment-list'),
#     path('create/', problem_views.comment_create, name='comment-create'),
#     path('<int:pk>/', problem_views.comment_detail_view, name='comment-detail'),
# ]

predict_patterns = [
    path('list/', normal_views.predict_list_view, name='predict-list'),
    path('detail/<int:pk>/', normal_views.predict_detail_view, name='predict-detail'),
    path('modal/<int:pk>/', normal_views.predict_modal_view, name='predict-modal'),
    path('register/', normal_views.predict_register_view, name='predict-register'),

    path('answer/input/<int:pk>/<str:subject_field>/',
         normal_views.predict_answer_input_view, name='predict-answer-input'),
    path('answer/confirm/<int:pk>/<str:subject_field>/',
         normal_views.predict_answer_confirm_view, name='predict-answer-confirm'),
]

lecture_patterns = [
    path('list/', normal_views.lecture_list_view, name='lecture-list'),
    path('detail/<int:pk>/', normal_views.lecture_detail_view, name='lecture-detail'),
    path('memo/<int:pk>/', normal_views.memo_lecture, name='memo-lecture'),
    path('tag/<int:pk>/', normal_views.tag_lecture, name='tag-lecture'),
]

study_patterns = [
    path('list/', normal_views.study_list_view, name='study-list'),
    path('detail/<int:pk>/', normal_views.study_detail_view, name='study-detail'),
    path('student/register/', normal_views.study_student_register_view, name='study-student-register'),
    path('answer/<int:pk>/', normal_views.study_answer_input_view, name='study-answer-input'),
    path('answer/confirm/<int:pk>/', normal_views.study_answer_confirm_view, name='study-answer-confirm'),

    path('curriculum/<str:organization>/<int:semester>/',
         normal_views.study_detail_redirect_view, name='study-detail-redirect'),
    path('curriculum/<str:organization>/<int:semester>/<int:homework_round>/',
         normal_views.study_answer_input_redirect_view, name='study-answer-input-redirect'),
]

urlpatterns = [
    path('', normal_views.official_problem_list_view, name='base'),
    path('annotation/', normal_views.annotation_view),

    path('admin/', include(admin_patterns)),
    path('official/', include(official_patterns)),
    # path('comment/', include(comment_patterns)),
    path('lecture/', include(lecture_patterns)),
    # path('predict/', include(predict_patterns)),
    path('study/', include(study_patterns)),
]

log/urls.py
from django.urls import path

from .views import create_request_log

app_name = 'log'

urlpatterns = [
    path('request/', create_request_log, name='request_log'),
]

a_psat/models/abstract_models.py
from django.db import models
from django.db.models.functions import Greatest

from . import choices


def get_default_statistics():
    return {'participants': 0, 'max': 0, 't10': 0, 't20': 0, 'avg': 0}


def get_default_problem_counts():
    return {'subject_1': 0, 'subject_2': 0, 'subject_3': 0, 'total': 0}


class Statistics(models.Model):
    department = models.CharField(
        max_length=40, choices=choices.statistics_department_choice, default='전체', verbose_name='직렬')
    subject_0 = models.JSONField(default=get_default_statistics, verbose_name='헌법')
    subject_1 = models.JSONField(default=get_default_statistics, verbose_name='언어논리')
    subject_2 = models.JSONField(default=get_default_statistics, verbose_name='자료해석')
    subject_3 = models.JSONField(default=get_default_statistics, verbose_name='상황판단')
    average = models.JSONField(default=get_default_statistics, verbose_name='PSAT')

    class Meta:
        abstract = True


class ExtendedStatistics(Statistics):
    filtered_subject_0 = models.JSONField(default=get_default_statistics, verbose_name='[필터링]헌법')
    filtered_subject_1 = models.JSONField(default=get_default_statistics, verbose_name='[필터링]언어논리')
    filtered_subject_2 = models.JSONField(default=get_default_statistics, verbose_name='[필터링]자료해석')
    filtered_subject_3 = models.JSONField(default=get_default_statistics, verbose_name='[필터링]상황판단')
    filtered_average = models.JSONField(default=get_default_statistics, verbose_name='[필터링]PSAT')

    class Meta:
        abstract = True


class Student(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')
    name = models.CharField(max_length=20, verbose_name='이름')
    serial = models.CharField(max_length=10, verbose_name='수험번호')
    password = models.CharField(max_length=10, default=0, verbose_name='비밀번호')

    class Meta:
        abstract = True

    @property
    def student_info(self):
        return f'{self.serial}-{self.name}'


class Answer(models.Model):
    answer = models.IntegerField(choices=choices.answer_choice, default=1, verbose_name='답안')

    class Meta:
        abstract = True


class AnswerCount(models.Model):
    problem = None
    count_1 = models.IntegerField(default=0, verbose_name='①')
    count_2 = models.IntegerField(default=0, verbose_name='②')
    count_3 = models.IntegerField(default=0, verbose_name='③')
    count_4 = models.IntegerField(default=0, verbose_name='④')
    count_5 = models.IntegerField(default=0, verbose_name='⑤')
    count_0 = models.IntegerField(default=0, verbose_name='미표기')
    count_multiple = models.IntegerField(default=0, verbose_name='중복표기')
    count_sum = models.IntegerField(default=0, verbose_name='총계')
    answer_predict = models.GeneratedField(
        expression=models.Case(
            models.When(
                models.Q(count_1=Greatest('count_1', 'count_2', 'count_3', 'count_4', 'count_5')),
                then=models.Value(1),
            ),
            models.When(
                models.Q(count_2=Greatest('count_1', 'count_2', 'count_3', 'count_4', 'count_5')),
                then=models.Value(2),
            ),
            models.When(
                models.Q(count_3=Greatest('count_1', 'count_2', 'count_3', 'count_4', 'count_5')),
                then=models.Value(3),
            ),
            models.When(
                models.Q(count_4=Greatest('count_1', 'count_2', 'count_3', 'count_4', 'count_5')),
                then=models.Value(4),
            ),
            models.When(
                models.Q(count_5=Greatest('count_1', 'count_2', 'count_3', 'count_4', 'count_5')),
                then=models.Value(5),
            ),
            default=None,
        ),
        output_field=models.IntegerField(),
        db_persist=True,
    )

    class Meta:
        abstract = True

    def get_answer_rate(self, ans: int):
        if self.count_sum:
            if 1 <= self.problem.answer <= 5:
                count_target = getattr(self, f'count_{ans}')
            else:
                answer_official_list = [int(digit) for digit in str(self.problem.answer)]
                count_target = sum(
                    getattr(self, f'count_{ans_official}') for ans_official in answer_official_list
                )
            return count_target * 100 / self.count_sum

    def get_answer_predict_rate(self):
        if self.count_sum:
            return getattr(self, f'count_{self.answer_predict}') * 100 / self.count_sum


class ExtendedAnswerCount(AnswerCount):
    filtered_count_1 = models.IntegerField(default=0, verbose_name='[필터링]①')
    filtered_count_2 = models.IntegerField(default=0, verbose_name='[필터링]②')
    filtered_count_3 = models.IntegerField(default=0, verbose_name='[필터링]③')
    filtered_count_4 = models.IntegerField(default=0, verbose_name='[필터링]④')
    filtered_count_5 = models.IntegerField(default=0, verbose_name='[필터링]⑤')
    filtered_count_0 = models.IntegerField(default=0, verbose_name='[필터링]미표기')
    filtered_count_multiple = models.IntegerField(default=0, verbose_name='[필터링]중복표기')
    filtered_count_sum = models.IntegerField(default=0, verbose_name='[필터링]총계')

    class Meta:
        abstract = True


class Score(models.Model):
    subject_0 = models.FloatField(null=True, blank=True, verbose_name='헌법')
    subject_1 = models.FloatField(null=True, blank=True, verbose_name='언어논리')
    subject_2 = models.FloatField(null=True, blank=True, verbose_name='자료해석')
    subject_3 = models.FloatField(null=True, blank=True, verbose_name='상황판단')
    sum = models.FloatField(null=True, blank=True, verbose_name='PSAT 총점')
    average = models.FloatField(null=True, blank=True, verbose_name='PSAT 평균')

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.sum = sum(score for i in range(1, 4) if (score := getattr(self, f'subject_{i}')) is not None)
        self.average = round(self.sum / 3, 1)
        super().save(*args, **kwargs)


class Rank(models.Model):
    subject_0 = models.IntegerField(null=True, blank=True, verbose_name='헌법')
    subject_1 = models.IntegerField(null=True, blank=True, verbose_name='언어논리')
    subject_2 = models.IntegerField(null=True, blank=True, verbose_name='자료해석')
    subject_3 = models.IntegerField(null=True, blank=True, verbose_name='상황판단')
    average = models.IntegerField(null=True, blank=True, verbose_name='PSAT')
    participants = models.IntegerField(null=True, blank=True, verbose_name='총 인원')

    class Meta:
        abstract = True

    def get_rank_raio(self, rank_code: str):
        _rank = getattr(self, rank_code)
        if self.participants:
            return _rank / self.participants


class ExtendedRank(Rank):
    filtered_subject_0 = models.IntegerField(null=True, blank=True, verbose_name='[필터링]헌법')
    filtered_subject_1 = models.IntegerField(null=True, blank=True, verbose_name='[필터링]언어논리')
    filtered_subject_2 = models.IntegerField(null=True, blank=True, verbose_name='[필터링]자료해석')
    filtered_subject_3 = models.IntegerField(null=True, blank=True, verbose_name='[필터링]상황판단')
    filtered_average = models.IntegerField(null=True, blank=True, verbose_name='[필터링]PSAT')
    filtered_participants = models.IntegerField(null=True, blank=True, verbose_name='[필터링]총 인원')

    class Meta:
        abstract = True

a_psat/templates/a_psat/snippets/admin_detail_button_update.html
<button class="btn btn-outline-secondary prevent_double_click"
        hx-headers='{"View-Type":"{{ view_type }}"}'
        hx-post="{{ update_url }}"
        data-bs-toggle="modal" data-bs-target="#modalContainer">
    {{ button_name }}
</button>

a_psat/templates/a_psat/snippets/admin_detail_predict_button_update.html
<button class="btn btn-outline-secondary prevent_double_click"
        hx-headers='{"View-Type":"{{ view_type }}"}'
        hx-post="{{ config.url_admin_predict_update }}"
        data-bs-toggle="modal" data-bs-target="#modalContainer">
    {{ button_name }}
</button>

a_psat/templates/a_psat/snippets/admin_detail_predict_catalog.html
{% load psat_filter %}
{% load humanize %}

<article class="table-responsive htmx-fade-in htmx-fade-out">
    <table class="table table-bordered table-striped align-middle m-0">
        <thead>
            <tr class="text-center table-warning align-middle">
                <th class="text-primary text-nowrap td-left-no-border" rowspan="2">ID</th>
                <th class="text-primary text-nowrap" rowspan="2">등수</th>
                <th class="text-primary text-nowrap" rowspan="2">이름<br/>(수험번호)</th>
                <th class="text-primary text-nowrap" rowspan="2">직렬</th>
                <th class="text-primary text-nowrap" rowspan="2">직렬/전체<br/>인원(명)</th>

                <th class="text-primary text-nowrap" colspan="3">PSAT</th>
                <th class="text-primary text-nowrap" colspan="3">헌법</th>
                <th class="text-primary text-nowrap" colspan="3">언어논리</th>
                <th class="text-primary text-nowrap" colspan="3">자료해석</th>
                <th class="text-primary text-nowrap" colspan="3">상황판단</th>
                <th class="text-primary text-nowrap" rowspan="2">등록 및<br/>답안 제출<br/>일시</th>
                <th class="text-primary text-nowrap" rowspan="2">제출<br/>답안<br/>개수</th>
                <th class="text-primary text-nowrap" rowspan="2">필터링<br/>여부</th>
                <th class="text-primary text-nowrap td-right-no-border" rowspan="2">프라임ID</th>
            </tr>

            <tr class="text-center table-warning align-middle">
                <th class="text-primary text-nowrap td-right-no-border" rowspan="2">총점<br/>(평균)</th>
                <th class="text-primary text-nowrap td-left-no-border td-right-no-border">전체<br/>석차</th>
                <th class="text-primary text-nowrap td-left-no-border">직렬<br/>석차</th>
                {% for _ in '1234' %}
                    <th class="text-primary text-nowrap td-right-no-border" rowspan="2">점수</th>
                    <th class="text-primary text-nowrap td-left-no-border td-right-no-border">전체<br/>석차</th>
                    <th class="text-primary text-nowrap td-left-no-border td-right-no-border">직렬<br/>석차</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for obj in catalog_data.page_obj %}
                <tr class="text-center">
                    <td class="text-nowrap td-left-no-border">{{ obj.id }}</td>
                    <td class="text-nowrap">{{ obj.rank_tot_avg|default:'' }}</td>
                    <td class="text-nowrap">
                        <a href="{{ obj.get_admin_predict_student_detail_url }}" target="score_print">
                            {{ obj.name }}<br/>({{ obj.serial }})
                        </a>
                    </td>
                    <td class="text-nowrap">
                        {{ obj.unit }}<br/>{{ obj.category.get_department_display }}
                    </td>
                    <td class="text-nowrap">
                        {% if obj.rank_dep_num %}{{ obj.rank_dep_num }} / {{ obj.rank_tot_num }}{% endif %}
                    </td>

                    <td class="text-nowrap td-right-no-border">
                        {% if obj.score_sum %}
                            {{ obj.score_sum|floatformat:1 }}<br/>({{ obj.score_avg|floatformat:1 }})
                        {% endif %}
                    </td>
                    <td class="text-nowrap td-left-no-border td-right-no-border">
                        {% if obj.rank_tot_avg and obj.rank_tot_num %}
                            {{ obj.rank_tot_avg }}<br/>
                            <span class="text-primary">{{ obj.rank_tot_avg|divide:obj.rank_tot_num|percentage|floatformat:1 }}</span>
                        {% endif %}
                    </td>
                    <td class="text-nowrap td-left-no-border">
                        {% if obj.rank_dep_avg and obj.rank_dep_num %}
                            {{ obj.rank_dep_avg }}<br/>
                            <span class="text-primary">{{ obj.rank_dep_avg|divide:obj.rank_dep_num|percentage|floatformat:1 }}</span>
                        {% endif %}
                    </td>

                    {% for _ in '0123' %}
                        {% cycle obj.score_0 obj.score_1 obj.score_2 obj.score_3 as score silent %}
                        {% cycle obj.rank_tot_0 obj.rank_tot_1 obj.rank_tot_2 obj.rank_tot_3 as rank_tot silent %}
                        {% cycle obj.rank_dep_0 obj.rank_dep_1 obj.rank_dep_2 obj.rank_dep_3 as rank_dep silent %}
                        <td class="align-top td-right-no-border">{{ score|floatformat:1 }}</td>
                        <td class="td-left-no-border td-right-no-border">
                            {% if rank_tot and obj.rank_tot_num %}
                                {{ rank_tot }}<br/>
                                <span class="text-primary">{{ rank_tot|divide:obj.rank_tot_num|percentage|floatformat:1 }}</span>
                            {% endif %}
                        </td>
                        <td class="text-nowrap td-left-no-border td-right-no-border">
                            {% if rank_dep and obj.rank_dep_num %}
                                {{ rank_dep }}<br/>
                                <span class="text-primary">{{ rank_dep|divide:obj.rank_dep_num|percentage|floatformat:1 }}</span>
                            {% endif %}
                        </td>
                    {% endfor %}
                    <td class="text-nowrap align-top">
                        {{ obj.created_at|date:'n/j G:i' }}<br/>
                        {{ obj.latest_answer_time|date:'n/j G:i' }}
                    </td>
                    <td class="text-nowrap">{{ obj.answer_count }}</td>
                    <td class="text-nowrap">
                        <div class="form-check form-switch d-flex justify-content-center">
                            <input class="form-check-input" type="checkbox" name="is_active" value="true" disabled aria-label="활성"
                                   {% if obj.is_filtered %}checked{% endif %}>
                        </div>
                    </td>
                    <td class="text-nowrap td-right-no-border">{{ obj.prime_id }}</td>
                </tr>
            {% empty %}
                <tr class="text-center">
                    <td class="text-nowrap" colspan="31">자료가 없습니다.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</article>

{% include 'a_prime/snippets/pagination.html' with page_obj=catalog_data.page_obj page_range=catalog_data.page_range header=catalog_data.header %}

a_psat/templates/a_psat/snippets/study_detail_lecture.html
<article class="table-responsive">
    <table class="table d-sm-none align-middle m-0">
        <tbody>
            {% for obj in lecture_context.page_obj %}
                <tr{% if obj.color_code %} class="table-{{ obj.color_code }}"{% endif %}>
                    <td class="text-nowrap">
                        <div class="fw-bold small mb-2">
                            {{ obj.lecture_number }}주차 - {{ obj.lecture_datetime|date:'n/j(D)' }}
                            {% if obj.lecture_round %}
                                <span class="text-primary">미니테스트 {{ obj.lecture_round }}회차</span>
                                {% if current_time > obj.lecture_open_datetime and current_time <= obj.homework_end_datetime %}
                                    <a class="btn btn-sm btn-outline-primary"
                                       href="{% url 'psat:study-answer-input-redirect' obj.curriculum.organization.name obj.curriculum.semester obj.lecture_round %}">
                                        답안 제출
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="fw-bold small">[{{ obj.get_lecture_theme_display }}]</span>
                            {% if obj.url_lecture %}
                                <a class="btn btn-sm btn-outline-primary ms-2" href="{{ obj.url_lecture }}">온라인 강의</a>
                            {% endif %}
                            {% if obj.url_lecture_list %}
                                <span class="text-primary fw-bold small ms-2">온라인 강의</span>
                                    {% for lecture_link in obj.url_lecture_list %}
                                        <a class="btn btn-sm btn-outline-primary ms-2" href="{{ lecture_link }}">#{{ forloop.counter }}</a>
                                    {% endfor %}
                            {% endif %}
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for topic in obj.lecture_topic %}
                                {% if topic.0 %}
                                    <li class="list-group-item bg-transparent px-0 border-0">
                                        <span class="badge rounded-pill bg-{{ obj.color_code|default_if_none:'success' }}{% if obj.color_code == 'warning' %} text-dark{% endif %}">
                                            {{ topic.0 }}
                                        </span>
                                        <span class="small">{{ topic.1 }}</span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% empty %}
                <tr class="text-center">
                    <td class="text-nowrap" colspan="22">자료가 없습니다.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <table class="table table-bordered d-none d-sm-table align-middle m-0">
        <thead>
            <tr class="text-center table-warning align-middle">
                <th class="text-primary text-nowrap td-left-no-border">주차</th>
                <th class="text-primary text-nowrap">미니테스트</th>
                <th class="text-primary text-nowrap td-right-no-border">강의 주제 및 토픽</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in lecture_context.page_obj %}
                <tr{% if obj.color_code %} class="table-{{ obj.color_code }}"{% endif %}>
                    <th class="text-nowrap text-center small td-left-no-border">
                        {{ obj.lecture_number }}주차<br/>
                        {{ obj.lecture_datetime|date:'n/j(D)' }}
                    </th>
                    <th class="text-nowrap text-center small">
                        {% if obj.lecture_round %}
                            {{ obj.lecture_round }}회차<br/>
                            {% if current_time > obj.lecture_open_datetime and current_time <= obj.homework_end_datetime %}
                                <a class="btn btn-sm btn-outline-primary"
                                   href="{% url 'psat:study-answer-input-redirect' obj.curriculum.organization.name obj.curriculum.semester obj.lecture_round %}">
                                    답안 제출
                                </a>
                            {% endif %}
                        {% endif %}
                    </th>
                    <td class="text-nowrap td-right-no-border">
                        <div class="d-flex align-items-center">
                            <span class="fw-bold small">[{{ obj.get_lecture_theme_display }}]</span>
                            {% if obj.url_lecture %}
                                <a class="btn btn-sm btn-outline-primary ms-2" href="{{ obj.url_lecture }}">온라인 강의</a>
                            {% endif %}
                            {% if obj.url_lecture_list %}
                                <span class="text-primary fw-bold small ms-2">온라인 강의</span>
                                    {% for lecture_link in obj.url_lecture_list %}
                                        <a class="btn btn-sm btn-outline-primary ms-2" href="{{ lecture_link }}">#{{ forloop.counter }}</a>
                                    {% endfor %}
                            {% endif %}
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for topic in obj.lecture_topic %}
                                {% if topic.0 %}
                                    <li class="list-group-item bg-transparent px-0 border-0">
                                        <span class="badge rounded-pill bg-{{ obj.color_code|default_if_none:'success' }}{% if obj.color_code == 'warning' %} text-dark{% endif %}">
                                            {{ topic.0 }}
                                        </span>
                                        <span class="small">{{ topic.1 }}</span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% empty %}
                <tr class="text-center">
                    <td class="text-nowrap" colspan="22">자료가 없습니다.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</article>

{% include 'a_psat/snippets/pagination.html' with page_obj=lecture_context.page_obj page_range=lecture_context.page_range header='lecture_list' %}