log/urls.py
from django.urls import path

from .views import create_request_log

app_name = 'log'

urlpatterns = [
    path('request/', create_request_log, name='request_log'),
]

score/urls.py
from django.urls import path, include

from score.views.psat_v4 import score_views, student_views
from score.views.prime_v3 import normal_views, admin_views
from score.views.predict_v1 import (
    normal_views as predict_normal_views,
    test_views as predict_test_views,
    admin_views as predict_admin_views,
)

app_name = 'score_old'

psat_urlpatterns = [
    path('', score_views.list_view, name='psat-list'),

    path('detail/', score_views.detail_view, name='psat-detail'),
    path('detail/<int:year>/<str:ex>/', score_views.detail_view, name='psat-detail-year-ex'),
    path('detail/filter/exam/', score_views.exam_filter, name='psat-filter'),

    path('submit/<int:problem_id>/', score_views.submit_view, name='psat-submit'),
    path('confirm/modal/', score_views.confirm_modal_view, name='psat-confirm-modal'),

    path('no_student/modal/<int:year>/<str:ex>/',
         student_views.no_student_modal_view, name='psat-no-student-modal'),

    path('student/create/modal/<int:year>/<str:ex>/',
         student_views.student_create_modal_view, name='psat-student-create-modal'),
    path('student/create/department/',
         student_views.student_create_department, name='psat-student-create-department'),
    path('student/create/',
         student_views.student_create_view, name='psat-student-create'),

    path('student/update/modal/<int:student_id>/',
         student_views.student_update_modal_view, name='psat-student-update-modal'),
    path('student/update/department/<int:student_id>/',
         student_views.student_update_department, name='psat-student-update-department'),
    path('student/update/<int:student_id>/',
         student_views.student_update_view, name='psat-student-update'),
]

prime_urlpatterns = [
    path('', normal_views.list_view, name='prime-list'),

    path('<int:year>/<int:round>/', normal_views.detail_view, name='prime-detail'),
    path('<int:year>/<int:round>/print/', normal_views.detail_print_view, name='prime-print'),

    path('<int:year>/<int:round>/no_open/', normal_views.no_open_modal_view, name='prime-no-open-modal'),
    path('<int:year>/<int:round>/no_student/', normal_views.no_student_modal_view, name='prime-no-student-modal'),

    path('predict/no_open/', normal_views.no_predict_open_modal, name='prime-no-predict-open-modal'),

    path('<int:year>/<int:round>/student/modal/',
         normal_views.student_connect_modal_view, name='prime-student-connect-modal'),
    path('<int:year>/<int:round>/student/connect/',
         normal_views.student_connect_view, name='prime-student-connect'),
    path('<int:year>/<int:round>/student/reset/',
         normal_views.student_reset_view, name='prime-student-reset'),
]

prime_admin_urlpatterns = [
    path('', admin_views.list_view, name='prime-admin-list'),
    path('student/', admin_views.list_student_view, name='prime-admin-list-student'),

    path('<int:year>/<int:round>/', admin_views.detail_view, name='prime-admin-detail'),
    path('search/<int:year>/<int:round>/', admin_views.catalog_view, name='prime-admin-catalog-year-round'),

    path('print/<int:year>/<int:round>/', admin_views.print_view, name='prime-admin-print'),
    path('print/<int:year>/<int:round>/<int:student_id>',
         admin_views.individual_student_print_view, name='prime-admin-individual-student-print'),

    path('export/transcript/<int:year>/<int:round>/',
         admin_views.export_transcript_to_pdf_view, name='prime-admin-export-transcript'),
    path('export/statistics/<int:year>/<int:round>/',
         admin_views.export_statistics_to_excel_view, name='prime-admin-export-statistics'),
    path('export/analysis/<int:year>/<int:round>/',
         admin_views.export_analysis_to_excel_view, name='prime-admin-export-analysis'),
    path('export/students_score/<int:year>/<int:round>/',
         admin_views.export_scores_to_excel_view, name='prime-admin-export-scores'),
]

predict_urlpatterns = [
    path('', predict_normal_views.index_view, name='predict-index'),
    path('test/', predict_test_views.TestView.as_view(), name='predict-test'),

    path('student/', predict_normal_views.student_create_view, name='predict-student-create'),
    path('student/department/',
         predict_normal_views.student_create_department, name='predict-student-create-department'),

    path('answer/<str:sub>/', predict_normal_views.answer_input_view, name='predict-answer-input'),
    path('answer/<str:sub>/submit/', predict_normal_views.answer_submit_view, name='predict-answer-submit'),
    path('answer/<str:sub>/confirm/', predict_normal_views.answer_confirm_view, name='predict-answer-confirm'),

    path('update/info_answer/', predict_normal_views.update_info_answer, name='predict-update-info-answer'),
    path('update/sheet_answer/', predict_normal_views.update_sheet_answer, name='predict-update-sheet-answer'),
    path('update/sheet_score/', predict_normal_views.update_sheet_score, name='predict-update-sheet-score'),
]

predict_admin_urlpatterns = [
    path('', predict_admin_views.list_view, name='predict-admin-list'),
    path('student/', predict_admin_views.list_student_view, name='predict-admin-list-student'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/', predict_admin_views.detail_view, name='predict-admin-detail'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/catalog/', predict_admin_views.catalog_view, name='predict-admin-catalog'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/user<int:user_id>/',
         predict_admin_views.individual_index_view, name='predict-admin-individual'),

    path('test/', predict_admin_views.test_view, name='predict-admin-test'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/answer/',
         predict_admin_views.update_answer, name='predict-admin-update-answer'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/score/',
         predict_admin_views.update_score, name='predict-admin-update-score'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/update/statistics/',
         predict_admin_views.update_statistics, name='predict-admin-update-statistics'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/print/', predict_admin_views.print_view, name='predict-admin-print'),
    # path('print/<int:year>/<int:round>/<int:student_id>',
    #      predict_admin_views.individual_student_print_view, name='predict-admin-individual-student-print'),

    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/transcript',
         predict_admin_views.export_transcript_to_pdf_view, name='predict-admin-export-transcript'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/statistics/',
         predict_admin_views.export_statistics_to_excel_view, name='predict-admin-export-statistics'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/analysis/',
         predict_admin_views.export_analysis_to_excel_view, name='predict-admin-export-analysis'),
    path('<str:category>/<int:year>/<str:ex>/<int:round>/export/students_score/',
         predict_admin_views.export_scores_to_excel_view, name='predict-admin-export-scores'),
    path('export/predict/google_sheet',
         predict_admin_views.export_predict_data_to_google_sheet_view, name='predict-admin-export-predict-to-google'),
]

urlpatterns = [
    path('psat/', include(psat_urlpatterns)),  # Psat score current version
    path('prime/', include(prime_urlpatterns)),  # Prime score current version
    path('prime/admin/', include(prime_admin_urlpatterns)),  # Prime_admin score current version
    path('predict/', include(predict_urlpatterns)),  # Predict score current version
    path('predict/admin/', include(predict_admin_urlpatterns)),  # Predict_admin score current version
]
#
# urlpatterns = [
#     path('psat/', include('score.urls_module.psat_v4')),  # Psat score current version
#     # path('psat/', include('score.urls_module.psat_v3')),  # Psat score current version
#     # path('psat_v2/', include('score.urls_module.psat_v2')),  # Psat score version 2.0
#     # path('psat_v1/', include('score.urls_module.psat_v1')),  # Psat score version 1.0
#
#     path('prime/', include('score.urls_module.prime_v3')),  # Prime score current version
#     # path('prime/', include('score.urls_module.prime_v2')),  # Prime score version 2.0
#     # path('prime_v1/', include('score.urls_module.prime_v1')),  # Prime score version 1.0
#
#     path('prime/admin/', include('score.urls_module.prime_admin_v3')),  # Prime_admin score current version
#     # path('prime/admin/', include('score.urls_module.prime_admin_v2')),  # Prime_admin score version 2.0
#     # path('prime_v1/admin/', include('score.urls_module.prime_admin_v1')),  # Prime_admin score version 1.0
#
#     path('predict/', include('score.urls_module.predict_v1')),  # Predict score current version
#     path('predict/admin/', include('score.urls_module.predict_admin_v1')),  # Predict_admin score current version
# ]

templates/score/predict_admin_v1/snippets/detail_catalog.html
{% load psat_filter %}
{% load slippers %}
{% load humanize %}
{% load partials %}

<div class="card-header">
    <div class="d-flex align-items-center">
        제{{ round }}회 | 성적 일람표
        <form method="POST" action="{% url 'score_old:prime-admin-export-transcript' year round %}"
              class="ms-auto">
            {% csrf_token %}
            <div class="btn-group">
                <a class="btn btn-sm btn-outline-secondary" title="Excel로 내보내기"
                   href="{% url 'score_old:predict-admin-export-scores' category year ex round %}">
                    Excel로 내보내기
                </a>
{#                <input name="student_ids" type="text" aria-label="Student IDs" hidden#}
{#                       value="{% for id in student_ids %}{{ id }}{% if not forloop.last %},{% endif %}{% endfor %}"/>#}
{#                <button class="btn btn-sm btn-outline-secondary"#}
{#                        title="PDF로 내보내기" type="submit">#}
{#                    PDF로 내보내기#}
{#                </button>#}
            </div>
        </form>
    </div>
</div>

<div class="card-body">
    <article class="table-responsive" hx-target="#main">
        <table class="table table-bordered table-striped small align-middle m-0">
            <thead>
                <tr class="text-center table-warning align-middle">
                    <th class="text-primary text-nowrap p-2" rowspan="3">ID</th>
                    <th class="text-primary text-nowrap p-2" rowspan="3">구분</th>
                    <th class="text-primary text-nowrap p-2" rowspan="3">등수</th>
                    <th class="text-primary text-nowrap p-2" rowspan="3">이름</th>
                    <th class="text-primary text-nowrap p-2" rowspan="3">수험번호</th>
                    <th class="text-primary text-nowrap p-2" rowspan="3">직렬</th>

                    <th class="text-primary text-nowrap p-2" colspan="6">PSAT</th>
                    <th class="text-primary text-nowrap p-2" colspan="5">헌법</th>
                    <th class="text-primary text-nowrap p-2" colspan="5">언어논리</th>
                    <th class="text-primary text-nowrap p-2" colspan="5">자료해석</th>
                    <th class="text-primary text-nowrap p-2" colspan="5">상황판단</th>
                </tr>

                <tr class="text-center table-warning align-middle">
                    <th class="text-primary text-nowrap p-2 td-right-no-border" rowspan="2">총점</th>
                    <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border" rowspan="2">평균</th>
                    <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border" colspan="2">전체 석차</th>
                    <th class="text-primary text-nowrap p-2 td-left-no-border" colspan="2">직렬 석차</th>
                    {% for _ in '1234' %}
                        <th class="text-primary text-nowrap p-2 td-right-no-border" rowspan="2">점수</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border" colspan="2">전체 석차</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border" colspan="2">직렬 석차</th>
                    {% endfor %}
                </tr>

                <tr class="text-center table-warning align-middle">
                    {% for _ in '12345' %}
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border">등</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border">%</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border">등</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border">%</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% if page_obj %}
                    {% for obj in page_obj %}
                        <tr class="text-center">
                            <td class="text-nowrap p-2">{{ obj.student.id }}</td>
                            <td class="text-nowrap p-2">
                                {% if obj.student.category is not None %}
                                    {{ obj.student.category }}
                                {% endif %}
                            </td>
                            <td class="text-nowrap p-2">{{ obj.rank_total_psat|default:'' }}</td>
                            <td class="text-nowrap p-2">
                                <a href="{% url 'score_old:predict-admin-individual' category year ex round obj.student.user_id %}"
                                   hx-boost="true" hx-push-url="true">
                                    {{ obj.student.name }}
                                </a>
                            </td>
                            <td class="text-nowrap p-2">{{ obj.student.serial }}</td>
                            <td class="text-nowrap p-2">{{ obj.student.department_id|get_department }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.score_psat|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.score_psat_avg|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_total_psat|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_ratio_total_psat|percentage|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_department_psat|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.rank_ratio_department_psat|percentage|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">
                                {% if obj.score_heonbeob %}
                                    {{ obj.score_heonbeob|floatformat:1 }}
                                {% else %}
                                    <span class="text-danger fw-bold">{{ obj.score_heonbeob|floatformat:1 }}</span>
                                {% endif %}
                            </td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_total_heonbeob|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_ratio_total_heonbeob|percentage|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_department_heonbeob|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.rank_ratio_department_heonbeob|percentage|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">
                                {% if obj.score_eoneo %}
                                    {{ obj.score_eoneo|floatformat:1 }}
                                {% else %}
                                    <span class="text-danger fw-bold">{{ obj.score_eoneo|floatformat:1 }}</span>
                                {% endif %}
                            </td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_total_eoneo|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_ratio_total_eoneo|percentage|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_department_eoneo|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.rank_ratio_department_eoneo|percentage|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">
                                {% if obj.score_jaryo %}
                                    {{ obj.score_jaryo|floatformat:1 }}
                                {% else %}
                                    <span class="text-danger fw-bold">{{ obj.score_jaryo|floatformat:1 }}</span>
                                {% endif %}
                            </td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_total_jaryo|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_ratio_total_jaryo|percentage|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_department_jaryo|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.rank_ratio_department_jaryo|percentage|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">
                                {% if obj.score_sanghwang %}
                                    {{ obj.score_sanghwang|floatformat:1 }}
                                {% else %}
                                    <span class="text-danger fw-bold">{{ obj.score_sanghwang|floatformat:1 }}</span>
                                {% endif %}
                            </td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_total_sanghwang|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_ratio_total_sanghwang|percentage|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.rank_department_sanghwang|default:'' }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.rank_ratio_department_sanghwang|percentage|floatformat:1 }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </article>

    <nav class="pt-3 me-auto ms-auto" aria-label="pagination" hx-target="#catalog">
        <ul class="pagination pagination-sm justify-content-center m-0">
            {% if page_obj.has_previous %}
                {% with page_num=page_obj.number|add:-1 chevron='left' %}

                    {% partialdef pagination_link inline=True %} {# pagination_link partial #}
                        <li class="page-item {{ status }}"
                            {% if status == 'active' %}aria-current="page"{% endif %}>
                            <a class="page-link" href=""
                                {% if status == 'disabled' %}
                                    tabindex="-1" aria-disabled="true"
                                {% else %}
                                    hx-get="{{ pagination_url }}&page={{ page_num }}"
                                {% endif %}>
                                {% if chevron %}
                                    <i class="fa-solid fa-chevron-{{ chevron }}"></i>
                                {% else %}
                                    {{ anchor_text }}
                                {% endif %}
                            </a>
                        </li>
                    {% endpartialdef pagination_link %}

                {% endwith %}
            {% endif %}

            {% for number in page_range %}
                {% with page_num=number anchor_text=number %}
                    {% if number == page_obj.number %}
                        {% with status='active' %}
                            {% partial pagination_link %}
                        {% endwith %}
                    {% elif number == page_obj.paginator.ELLIPSIS %}
                        {% with status='disabled' %}
                            {% partial pagination_link %}
                        {% endwith %}
                    {% else %}
                        {% partial pagination_link %}
                    {% endif %}
                {% endwith %}
            {% endfor %}

            {% if page_obj.has_next %}
                {% with page_num=page_obj.number|add:1 chevron='right' %}
                    {% partial pagination_link %}
                {% endwith %}
            {% endif %}
        </ul>
    </nav><!-- Pagination End -->
</div>

templates/score/predict_admin_v1/snippets/detail_statistics.html
{% load humanize %}

<div class="card-header">
    <div class="d-flex align-items-center">
        <span>제{{ round }}회 | 성적 통계</span>
        <div class="btn-group ms-auto">
            <a class="btn btn-sm btn-outline-secondary" title="목록" hx-push-url="true"
               href="{% url 'score_old:prime-admin-list' %}" hx-post="{% url 'score_old:predict-admin-list' %}">
                목록
            </a>
            <a class="btn btn-sm btn-outline-secondary" title="정답 업데이트"
               hx-confirm="정답 자료를 업데이트하시겠습니까?" href=""
               hx-get="{% url 'score_old:predict-admin-update-answer' category year ex round %}"
               hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
               data-bs-toggle="modal" data-bs-target="#modalContainer">
                정답 업데이트
            </a>
            <a class="btn btn-sm btn-outline-secondary" title="업데이트"
               hx-confirm="성적 자료를 업데이트하시겠습니까?" href=""
               hx-get="{% url 'score_old:predict-admin-update-score' category year ex round %}"
               hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
               data-bs-toggle="modal" data-bs-target="#modalContainer">
                성적 업데이트
            </a>
            <a class="btn btn-sm btn-outline-secondary" title="업데이트"
               hx-confirm="통계 자료를 업데이트하시겠습니까?" href=""
               hx-get="{% url 'score_old:predict-admin-update-statistics' category year ex round %}"
               hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
               data-bs-toggle="modal" data-bs-target="#modalContainer">
                통계 업데이트
            </a>
            <a class="btn btn-sm btn-outline-secondary" title="Excel로 내보내기"
               href="{% url 'score_old:predict-admin-export-statistics' category year ex round %}">
                Excel로 내보내기
            </a>
{#            <a class="btn btn-sm btn-outline-secondary" title="인쇄하기"#}
{#               href="{% url 'score_old:prime-admin-print' year round %}" target="_blank">#}
{#                인쇄하기#}
{#            </a>#}
{#            <a class="btn btn-sm btn-outline-secondary" title="Excel로 내보내기"#}
{#               href="{% url 'score_old:prime-admin-export-statistics' year round %}">#}
{#                Excel로 내보내기#}
{#            </a>#}
        </div>
    </div>
</div>

<div class="card-body">
    <article class="table-responsive">
        <table class="table table-bordered table-striped small align-middle m-0">
            <thead>
                <tr class="text-center table-warning align-middle">
                    <th class="text-primary text-nowrap p-2" rowspan="2">직렬</th>
                    <th class="text-primary text-nowrap p-2" rowspan="2">응시 인원</th>
                    <th class="text-primary text-nowrap p-2" colspan="4">PSAT</th>
                    <th class="text-primary text-nowrap p-2" colspan="4">헌법</th>
                    <th class="text-primary text-nowrap p-2" colspan="4">언어논리</th>
                    <th class="text-primary text-nowrap p-2" colspan="4">자료해석</th>
                    <th class="text-primary text-nowrap p-2" colspan="4">상황판단</th>
                </tr>

                <tr class="text-center table-warning align-middle">
                    {% for _ in '12345' %}
                        <th class="text-primary text-nowrap p-2 td-right-no-border">최고<br/>점수</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border">상위<br/>10%</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border td-right-no-border">상위<br/>20%</th>
                        <th class="text-primary text-nowrap p-2 td-left-no-border">평균<br/>점수</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% if statistics %}
                    {% for obj in statistics %}
                        <tr class="text-center">
                            <td class="text-nowrap p-2">{{ obj.department }}</td>
                            <td class="text-nowrap p-2">{{ obj.num_students|intcomma }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.max_score_psat_avg|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_10_psat_avg|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_20_psat_avg|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.avg_score_psat_avg|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.max_score_heonbeob|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_10_heonbeob|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_20_heonbeob|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.avg_score_heonbeob|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.max_score_eoneo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_10_eoneo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_20_eoneo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.avg_score_eoneo|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.max_score_jaryo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_10_jaryo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_20_jaryo|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.avg_score_jaryo|floatformat:1 }}</td>

                            <td class="text-nowrap p-2 td-right-no-border">{{ obj.max_score_sanghwang|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_10_sanghwang|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border td-right-no-border">{{ obj.top_score_20_sanghwang|floatformat:1 }}</td>
                            <td class="text-nowrap p-2 td-left-no-border">{{ obj.avg_score_sanghwang|floatformat:1 }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </article>
</div>

templates/score/predict_admin_v1/snippets/list_exam_list.html
<div class="card-header">
    <div class="d-flex align-items-center">
        <span>시험 목록 | 관리자 페이지</span>
        {% if user.is_authenticated %}
            <div class="btn-group ms-auto">
                <a class="btn btn-sm btn-outline-secondary" title="구글시트 내보내기"
                   hx-confirm="구글시트로 내보내시겠습니까?" href=""
                   hx-get="{% url 'score_old:predict-admin-export-predict-to-google' %}"
                   hx-target="#modalContainer" hx-swap="innerHTML" hx-push-url="false"
                   data-bs-toggle="modal" data-bs-target="#modalContainer">
                    구글시트로 내보내기
                </a>
            </div>
        {% endif %}
    </div>
</div>

<div class="card-body">
    <article class="table-responsive col-md-6 ms-auto me-auto">
        <table class="table table-bordered table-striped small align-middle">
            <thead>
                <tr class="text-center table-warning align-middle">
                    <th class="text-primary text-nowrap p-2" rowspan="2">시험일</th>
                    <th class="text-primary text-nowrap p-2" rowspan="2">연도</th>
                    <th class="text-primary text-nowrap p-2" rowspan="2">시험</th>
                    <th class="text-primary text-nowrap p-2" rowspan="2">회차</th>
                </tr>
            </thead>
            <tbody>
                {% if exam_page_obj %}
                    {% for obj in exam_page_obj %}
                        <tr class="text-center">
                            <td class="text-nowrap p-2">
                                {{ obj.date|date:'Y.n.j(D)' }}
                                <a class="btn btn-sm btn-outline-primary" hx-boost="true"
                                   href="{% url 'score_old:predict-admin-detail' obj.category obj.year obj.ex obj.round %}">
                                    클릭
                                </a>
                            </td>
                            <td class="text-nowrap p-2">{{ obj.year }}</td>
                            <td class="text-nowrap p-2">{{ obj.exam }}</td>
                            <td class="text-nowrap p-2">
                                {% if obj.round %}{{ obj.round }}{% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </article>
</div>